-- ════════════════════════════════════════════════════════════════
-- 0003_seed_medicines.sql — global medicine list (clinic_id = NULL)
-- Curated common Indian OPD drugs for autocomplete. Clinics may add
-- their own rows; this seed is the shared baseline. Expand as needed.
-- ════════════════════════════════════════════════════════════════

insert into medicines (clinic_id, name, form, strength) values
-- Analgesics / Antipyretics
(null,'Paracetamol','Tab','500 mg'),
(null,'Paracetamol','Tab','650 mg'),
(null,'Dolo 650','Tab','650 mg'),
(null,'Crocin','Tab','500 mg'),
(null,'Ibuprofen','Tab','400 mg'),
(null,'Combiflam','Tab','400/325 mg'),
(null,'Diclofenac','Tab','50 mg'),
(null,'Aceclofenac','Tab','100 mg'),
(null,'Zerodol-P','Tab','100/325 mg'),
(null,'Naproxen','Tab','250 mg'),
(null,'Tramadol','Tab','50 mg'),
(null,'Aspirin','Tab','75 mg'),
-- Antibiotics
(null,'Amoxicillin','Cap','500 mg'),
(null,'Amoxicillin + Clavulanate','Tab','625 mg'),
(null,'Augmentin','Tab','625 mg'),
(null,'Azithromycin','Tab','500 mg'),
(null,'Azithral','Tab','500 mg'),
(null,'Cefixime','Tab','200 mg'),
(null,'Taxim-O','Tab','200 mg'),
(null,'Cephalexin','Cap','500 mg'),
(null,'Ciprofloxacin','Tab','500 mg'),
(null,'Levofloxacin','Tab','500 mg'),
(null,'Ofloxacin','Tab','200 mg'),
(null,'Ofloxacin + Ornidazole','Tab','200/500 mg'),
(null,'Doxycycline','Cap','100 mg'),
(null,'Metronidazole','Tab','400 mg'),
(null,'Clindamycin','Cap','300 mg'),
(null,'Nitrofurantoin','Tab','100 mg'),
(null,'Cotrimoxazole','Tab','800/160 mg'),
(null,'Cefpodoxime','Tab','200 mg'),
(null,'Faropenem','Tab','200 mg'),
-- Antacids / GI
(null,'Pantoprazole','Tab','40 mg'),
(null,'Pan 40','Tab','40 mg'),
(null,'Omeprazole','Cap','20 mg'),
(null,'Rabeprazole','Tab','20 mg'),
(null,'Rantac','Tab','150 mg'),
(null,'Domperidone','Tab','10 mg'),
(null,'Ondansetron','Tab','4 mg'),
(null,'Emeset','Tab','4 mg'),
(null,'Digene','Tab','—'),
(null,'Gelusil','Susp','—'),
(null,'Sucralfate','Susp','1 g/10ml'),
(null,'Dicyclomine','Tab','10 mg'),
(null,'Meftal Spas','Tab','—'),
(null,'Loperamide','Tab','2 mg'),
(null,'ORS','Sachet','—'),
(null,'Lactulose','Syr','10 g/15ml'),
(null,'Isabgol','Powder','—'),
(null,'Bisacodyl','Tab','5 mg'),
-- Antihistamines / Cold
(null,'Cetirizine','Tab','10 mg'),
(null,'Levocetirizine','Tab','5 mg'),
(null,'Levocetirizine + Montelukast','Tab','5/10 mg'),
(null,'Montelukast','Tab','10 mg'),
(null,'Fexofenadine','Tab','120 mg'),
(null,'Chlorpheniramine','Tab','4 mg'),
(null,'Cheston Cold','Tab','—'),
(null,'Sinarest','Tab','—'),
(null,'Ambroxol','Syr','30 mg/5ml'),
(null,'Ascoril','Syr','—'),
(null,'Grilinctus','Syr','—'),
(null,'Dextromethorphan','Syr','—'),
-- Respiratory
(null,'Salbutamol','Inhaler','100 mcg'),
(null,'Asthalin','Inhaler','100 mcg'),
(null,'Budesonide','Inhaler','200 mcg'),
(null,'Deriphyllin','Tab','—'),
(null,'Theophylline','Tab','100 mg'),
-- Antidiabetics
(null,'Metformin','Tab','500 mg'),
(null,'Metformin','Tab','1000 mg'),
(null,'Glimepiride','Tab','1 mg'),
(null,'Glimepiride + Metformin','Tab','1/500 mg'),
(null,'Gliclazide','Tab','80 mg'),
(null,'Teneligliptin','Tab','20 mg'),
(null,'Sitagliptin','Tab','100 mg'),
(null,'Vildagliptin','Tab','50 mg'),
(null,'Insulin (Human Mixtard)','Inj','—'),
-- Cardiovascular / BP
(null,'Amlodipine','Tab','5 mg'),
(null,'Telmisartan','Tab','40 mg'),
(null,'Telmisartan + Amlodipine','Tab','40/5 mg'),
(null,'Losartan','Tab','50 mg'),
(null,'Ramipril','Tab','5 mg'),
(null,'Enalapril','Tab','5 mg'),
(null,'Atenolol','Tab','50 mg'),
(null,'Metoprolol','Tab','50 mg'),
(null,'Nebivolol','Tab','5 mg'),
(null,'Hydrochlorothiazide','Tab','12.5 mg'),
(null,'Furosemide','Tab','40 mg'),
(null,'Atorvastatin','Tab','10 mg'),
(null,'Rosuvastatin','Tab','10 mg'),
(null,'Clopidogrel','Tab','75 mg'),
-- Vitamins / Supplements
(null,'Vitamin D3 (60K)','Sachet','60000 IU'),
(null,'Calcium + Vitamin D3','Tab','500 mg'),
(null,'Shelcal','Tab','500 mg'),
(null,'Vitamin B-Complex','Tab','—'),
(null,'Becosules','Cap','—'),
(null,'Folic Acid','Tab','5 mg'),
(null,'Ferrous Ascorbate + Folic Acid','Tab','100 mg'),
(null,'Livogen','Tab','—'),
(null,'Methylcobalamin','Tab','1500 mcg'),
(null,'Vitamin C','Tab','500 mg'),
(null,'Zincovit','Tab','—'),
(null,'Multivitamin','Tab','—'),
-- Steroids / Anti-inflammatory
(null,'Prednisolone','Tab','10 mg'),
(null,'Deflazacort','Tab','6 mg'),
(null,'Dexamethasone','Tab','0.5 mg'),
(null,'Betamethasone','Cream','—'),
(null,'Hydrocortisone','Cream','1%'),
-- Topical
(null,'Mupirocin','Ointment','2%'),
(null,'Clotrimazole','Cream','1%'),
(null,'Ketoconazole','Cream','2%'),
(null,'Silver Sulfadiazine','Cream','1%'),
(null,'Framycetin','Cream','1%'),
(null,'Calamine','Lotion','—'),
-- Antifungal / Antiviral (oral)
(null,'Fluconazole','Tab','150 mg'),
(null,'Itraconazole','Cap','100 mg'),
(null,'Terbinafine','Tab','250 mg'),
(null,'Acyclovir','Tab','400 mg'),
-- Muscle relaxants / Others
(null,'Thiocolchicoside','Tab','4 mg'),
(null,'Chlorzoxazone','Tab','250 mg'),
(null,'Serratiopeptidase','Tab','10 mg'),
(null,'Pregabalin','Cap','75 mg'),
(null,'Gabapentin','Cap','300 mg'),
(null,'Amitriptyline','Tab','10 mg'),
-- Eye / ENT drops
(null,'Moxifloxacin Eye Drops','Drops','0.5%'),
(null,'Ciprofloxacin Ear Drops','Drops','0.3%'),
(null,'Xylometazoline Nasal Drops','Drops','0.1%'),
(null,'Otrivin','Nasal Spray','—'),
-- Thyroid
(null,'Thyroxine','Tab','50 mcg'),
(null,'Thyronorm','Tab','50 mcg');
