-- v7 Wave 1: expanded global medicine list (clinic_id = NULL).
--
-- SCOPE AND LIMITS — read before relying on this.
-- This is a CURATED, NON-EXHAUSTIVE list of commonly prescribed Indian OPD
-- drugs, covering generics plus widely-recognised brand names. It is NOT a
-- licensed drug database and does not claim completeness. Clinics reach full
-- coverage by importing an authoritative dataset (CDSCO/NPPA published lists or
-- a licensed drug DB) through Settings → Medicines → Import, which adds rows
-- scoped to that clinic.
--
-- `composition` must always name the ACTIVE INGREDIENTS, because the clinical
-- safety engine (src/lib/clinical/safety.ts) matches allergies and interactions
-- on ingredients, never on brand names. A row with a wrong or missing
-- composition silently weakens allergy checking for that drug.
--
-- Strength is NULL where a product has no single meaningful strength
-- (combination syrups, powders, some topicals).
--
-- `on conflict do nothing` + the medicines_dedupe_uniq index from 0017 make
-- this file safe to re-run.

insert into medicines (clinic_id, name, form, strength, composition) values

-- ── Analgesics / Antipyretics / NSAIDs ────────────────────────────────────
(null,'Paracetamol','Tab','325 mg','Paracetamol'),
(null,'Paracetamol','Syr','250 mg/5ml','Paracetamol'),
(null,'Paracetamol','Drops','100 mg/ml','Paracetamol'),
(null,'Paracetamol','Inj','150 mg/ml','Paracetamol'),
(null,'Calpol','Syr','250 mg/5ml','Paracetamol'),
(null,'Calpol','Tab','500 mg','Paracetamol'),
(null,'Dolo 500','Tab','500 mg','Paracetamol'),
(null,'Crocin Advance','Tab','500 mg','Paracetamol'),
(null,'Ibuprofen','Tab','200 mg','Ibuprofen'),
(null,'Ibuprofen','Tab','600 mg','Ibuprofen'),
(null,'Ibuprofen','Syr','100 mg/5ml','Ibuprofen'),
(null,'Ibuprofen + Paracetamol','Tab','400/325 mg','Ibuprofen + Paracetamol'),
(null,'Brufen','Tab','400 mg','Ibuprofen'),
(null,'Diclofenac','Tab','75 mg','Diclofenac'),
(null,'Diclofenac','Inj','75 mg/3ml','Diclofenac'),
(null,'Diclofenac','Gel','1%','Diclofenac'),
(null,'Voveran','Tab','50 mg','Diclofenac'),
(null,'Voveran SR','Tab','100 mg','Diclofenac'),
(null,'Aceclofenac','Tab','200 mg','Aceclofenac'),
(null,'Aceclofenac + Paracetamol','Tab','100/325 mg','Aceclofenac + Paracetamol'),
(null,'Aceclofenac + Paracetamol + Serratiopeptidase','Tab','100/325/15 mg','Aceclofenac + Paracetamol + Serratiopeptidase'),
(null,'Zerodol','Tab','100 mg','Aceclofenac'),
(null,'Zerodol-SP','Tab','100/325/15 mg','Aceclofenac + Paracetamol + Serratiopeptidase'),
(null,'Hifenac','Tab','100 mg','Aceclofenac'),
(null,'Naproxen','Tab','500 mg','Naproxen'),
(null,'Naproxen + Domperidone','Tab','500/10 mg','Naproxen + Domperidone'),
(null,'Mefenamic Acid','Tab','500 mg','Mefenamic Acid'),
(null,'Mefenamic Acid','Syr','100 mg/5ml','Mefenamic Acid'),
(null,'Meftal','Tab','500 mg','Mefenamic Acid'),
(null,'Meftal-P','Syr','100 mg/5ml','Mefenamic Acid + Paracetamol'),
(null,'Etoricoxib','Tab','60 mg','Etoricoxib'),
(null,'Etoricoxib','Tab','90 mg','Etoricoxib'),
(null,'Etoricoxib','Tab','120 mg','Etoricoxib'),
(null,'Nucoxia','Tab','90 mg','Etoricoxib'),
(null,'Piroxicam','Tab','20 mg','Piroxicam'),
(null,'Indomethacin','Cap','25 mg','Indomethacin'),
(null,'Ketorolac','Tab','10 mg','Ketorolac'),
(null,'Ketorolac','Inj','30 mg/ml','Ketorolac'),
(null,'Nimesulide','Tab','100 mg','Nimesulide'),
(null,'Tramadol','Cap','100 mg','Tramadol'),
(null,'Tramadol + Paracetamol','Tab','37.5/325 mg','Tramadol + Paracetamol'),
(null,'Ultracet','Tab','37.5/325 mg','Tramadol + Paracetamol'),
(null,'Aspirin','Tab','150 mg','Aspirin'),
(null,'Aspirin','Tab','325 mg','Aspirin'),
(null,'Ecosprin','Tab','75 mg','Aspirin'),
(null,'Ecosprin','Tab','150 mg','Aspirin'),
(null,'Trypsin + Chymotrypsin','Tab','50000 AU','Trypsin + Chymotrypsin'),
(null,'Chymoral Forte','Tab','100000 AU','Trypsin + Chymotrypsin'),

-- ── Antibiotics: penicillins ──────────────────────────────────────────────
(null,'Amoxicillin','Cap','250 mg','Amoxicillin'),
(null,'Amoxicillin','Syr','125 mg/5ml','Amoxicillin'),
(null,'Amoxicillin','Syr','250 mg/5ml','Amoxicillin'),
(null,'Amoxicillin + Clavulanic Acid','Tab','1 g','Amoxicillin + Clavulanic Acid'),
(null,'Amoxicillin + Clavulanic Acid','Syr','228 mg/5ml','Amoxicillin + Clavulanic Acid'),
(null,'Amoxicillin + Clavulanic Acid','Inj','1.2 g','Amoxicillin + Clavulanic Acid'),
(null,'Augmentin Duo','Syr','228 mg/5ml','Amoxicillin + Clavulanic Acid'),
(null,'Clavam','Tab','625 mg','Amoxicillin + Clavulanic Acid'),
(null,'Moxikind-CV','Tab','625 mg','Amoxicillin + Clavulanic Acid'),
(null,'Ampicillin','Cap','500 mg','Ampicillin'),
(null,'Ampicillin + Cloxacillin','Cap','250/250 mg','Ampicillin + Cloxacillin'),
(null,'Cloxacillin','Cap','500 mg','Cloxacillin'),
(null,'Penicillin V','Tab','500 mg','Phenoxymethylpenicillin'),
(null,'Benzathine Penicillin','Inj','12 Lakh IU','Benzathine Benzylpenicillin'),
(null,'Piperacillin + Tazobactam','Inj','4.5 g','Piperacillin + Tazobactam'),

-- ── Antibiotics: cephalosporins ───────────────────────────────────────────
(null,'Cefixime','Tab','100 mg','Cefixime'),
(null,'Cefixime','Syr','50 mg/5ml','Cefixime'),
(null,'Cefixime + Ofloxacin','Tab','200/200 mg','Cefixime + Ofloxacin'),
(null,'Cefixime + Clavulanic Acid','Tab','200/125 mg','Cefixime + Clavulanic Acid'),
(null,'Zifi','Tab','200 mg','Cefixime'),
(null,'Cefpodoxime','Tab','100 mg','Cefpodoxime'),
(null,'Cefpodoxime + Clavulanic Acid','Tab','200/125 mg','Cefpodoxime + Clavulanic Acid'),
(null,'Cefuroxime','Tab','500 mg','Cefuroxime'),
(null,'Cefuroxime','Tab','250 mg','Cefuroxime'),
(null,'Cephalexin','Cap','250 mg','Cephalexin'),
(null,'Cephalexin','Syr','125 mg/5ml','Cephalexin'),
(null,'Cefadroxil','Tab','500 mg','Cefadroxil'),
(null,'Ceftriaxone','Inj','1 g','Ceftriaxone'),
(null,'Ceftriaxone + Sulbactam','Inj','1.5 g','Ceftriaxone + Sulbactam'),
(null,'Cefotaxime','Inj','1 g','Cefotaxime'),
(null,'Ceftazidime','Inj','1 g','Ceftazidime'),
(null,'Cefdinir','Cap','300 mg','Cefdinir'),

-- ── Antibiotics: macrolides, tetracyclines, quinolones, others ────────────
(null,'Azithromycin','Tab','250 mg','Azithromycin'),
(null,'Azithromycin','Syr','200 mg/5ml','Azithromycin'),
(null,'Azithral','Syr','200 mg/5ml','Azithromycin'),
(null,'Azee','Tab','500 mg','Azithromycin'),
(null,'Clarithromycin','Tab','500 mg','Clarithromycin'),
(null,'Erythromycin','Tab','250 mg','Erythromycin'),
(null,'Roxithromycin','Tab','150 mg','Roxithromycin'),
(null,'Doxycycline','Tab','100 mg','Doxycycline'),
(null,'Minocycline','Cap','100 mg','Minocycline'),
(null,'Ciprofloxacin','Tab','250 mg','Ciprofloxacin'),
(null,'Ciprofloxacin + Tinidazole','Tab','500/600 mg','Ciprofloxacin + Tinidazole'),
(null,'Cifran','Tab','500 mg','Ciprofloxacin'),
(null,'Levofloxacin','Tab','250 mg','Levofloxacin'),
(null,'Levofloxacin','Tab','750 mg','Levofloxacin'),
(null,'Ofloxacin','Tab','400 mg','Ofloxacin'),
(null,'Ofloxacin + Ornidazole','Susp','50/125 mg/5ml','Ofloxacin + Ornidazole'),
(null,'Norfloxacin','Tab','400 mg','Norfloxacin'),
(null,'Moxifloxacin','Tab','400 mg','Moxifloxacin'),
(null,'Metronidazole','Tab','200 mg','Metronidazole'),
(null,'Metronidazole','Syr','200 mg/5ml','Metronidazole'),
(null,'Metrogyl','Tab','400 mg','Metronidazole'),
(null,'Tinidazole','Tab','500 mg','Tinidazole'),
(null,'Ornidazole','Tab','500 mg','Ornidazole'),
(null,'Secnidazole','Tab','1 g','Secnidazole'),
(null,'Nitrofurantoin','Tab','50 mg','Nitrofurantoin'),
(null,'Fosfomycin','Sachet','3 g','Fosfomycin'),
(null,'Rifaximin','Tab','400 mg','Rifaximin'),
(null,'Linezolid','Tab','600 mg','Linezolid'),
(null,'Amikacin','Inj','500 mg','Amikacin'),
(null,'Gentamicin','Inj','80 mg','Gentamicin'),
(null,'Meropenem','Inj','1 g','Meropenem'),
(null,'Vancomycin','Inj','500 mg','Vancomycin'),

-- ── Antitubercular ────────────────────────────────────────────────────────
(null,'Isoniazid','Tab','300 mg','Isoniazid'),
(null,'Rifampicin','Cap','450 mg','Rifampicin'),
(null,'Rifampicin','Cap','600 mg','Rifampicin'),
(null,'Pyrazinamide','Tab','750 mg','Pyrazinamide'),
(null,'Ethambutol','Tab','800 mg','Ethambutol'),
(null,'4-FDC (HRZE)','Tab','75/150/400/275 mg','Isoniazid + Rifampicin + Pyrazinamide + Ethambutol'),
(null,'Pyridoxine','Tab','40 mg','Pyridoxine'),

-- ── Antifungals / Antivirals / Antiparasitics ─────────────────────────────
(null,'Fluconazole','Tab','200 mg','Fluconazole'),
(null,'Fluconazole','Tab','400 mg','Fluconazole'),
(null,'Itraconazole','Cap','200 mg','Itraconazole'),
(null,'Terbinafine','Tab','500 mg','Terbinafine'),
(null,'Griseofulvin','Tab','250 mg','Griseofulvin'),
(null,'Voriconazole','Tab','200 mg','Voriconazole'),
(null,'Acyclovir','Tab','800 mg','Acyclovir'),
(null,'Acyclovir','Cream','5%','Acyclovir'),
(null,'Valacyclovir','Tab','500 mg','Valacyclovir'),
(null,'Oseltamivir','Cap','75 mg','Oseltamivir'),
(null,'Albendazole','Tab','400 mg','Albendazole'),
(null,'Albendazole','Susp','200 mg/5ml','Albendazole'),
(null,'Mebendazole','Tab','100 mg','Mebendazole'),
(null,'Ivermectin','Tab','12 mg','Ivermectin'),
(null,'Diethylcarbamazine','Tab','100 mg','Diethylcarbamazine'),
(null,'Hydroxychloroquine','Tab','200 mg','Hydroxychloroquine'),
(null,'Chloroquine','Tab','250 mg','Chloroquine'),
(null,'Artemether + Lumefantrine','Tab','80/480 mg','Artemether + Lumefantrine'),
(null,'Primaquine','Tab','7.5 mg','Primaquine'),

-- ── GI: acid suppression ──────────────────────────────────────────────────
(null,'Pantoprazole','Tab','20 mg','Pantoprazole'),
(null,'Pantoprazole','Inj','40 mg','Pantoprazole'),
(null,'Pantoprazole + Domperidone','Cap','40/30 mg','Pantoprazole + Domperidone'),
(null,'Pantocid','Tab','40 mg','Pantoprazole'),
(null,'Pantop','Tab','40 mg','Pantoprazole'),
(null,'Omeprazole','Cap','40 mg','Omeprazole'),
(null,'Esomeprazole','Tab','40 mg','Esomeprazole'),
(null,'Nexpro','Tab','40 mg','Esomeprazole'),
(null,'Rabeprazole','Tab','10 mg','Rabeprazole'),
(null,'Rabeprazole + Domperidone','Cap','20/30 mg','Rabeprazole + Domperidone'),
(null,'Razo','Tab','20 mg','Rabeprazole'),
(null,'Lansoprazole','Cap','30 mg','Lansoprazole'),
(null,'Ranitidine','Tab','150 mg','Ranitidine'),
(null,'Famotidine','Tab','40 mg','Famotidine'),
(null,'Sucralfate','Susp','1 g/10ml','Sucralfate'),

-- ── GI: motility, antiemetics, antispasmodics ─────────────────────────────
(null,'Domperidone','Syr','1 mg/ml','Domperidone'),
(null,'Ondansetron','Tab','8 mg','Ondansetron'),
(null,'Ondansetron','Syr','2 mg/5ml','Ondansetron'),
(null,'Ondansetron','Inj','2 mg/ml','Ondansetron'),
(null,'Metoclopramide','Tab','10 mg','Metoclopramide'),
(null,'Metoclopramide','Inj','5 mg/ml','Metoclopramide'),
(null,'Doxylamine + Pyridoxine','Tab','10/10 mg','Doxylamine + Pyridoxine'),
(null,'Dicyclomine + Paracetamol','Tab','20/500 mg','Dicyclomine + Paracetamol'),
(null,'Drotaverine','Tab','40 mg','Drotaverine'),
(null,'Drotin','Tab','40 mg','Drotaverine'),
(null,'Hyoscine Butylbromide','Tab','10 mg','Hyoscine Butylbromide'),
(null,'Buscopan','Tab','10 mg','Hyoscine Butylbromide'),
(null,'Mebeverine','Tab','135 mg','Mebeverine'),
(null,'Simethicone','Drops','40 mg/ml','Simethicone'),
(null,'Colicaid','Drops',null,'Dill Oil + Fennel + Simethicone'),

-- ── GI: laxatives, antidiarrhoeals, probiotics, hepatic ───────────────────
(null,'Lactulose','Syr',null,'Lactulose'),
(null,'Duphalac','Syr',null,'Lactulose'),
(null,'Polyethylene Glycol','Powder','17 g','Macrogol 3350'),
(null,'Sodium Picosulfate','Drops','7.5 mg/ml','Sodium Picosulfate'),
(null,'Cremaffin','Syr',null,'Milk of Magnesia + Liquid Paraffin'),
(null,'Racecadotril','Cap','100 mg','Racecadotril'),
(null,'Racecadotril','Sachet','10 mg','Racecadotril'),
(null,'Saccharomyces boulardii','Sachet','250 mg','Saccharomyces boulardii'),
(null,'Econorm','Sachet','250 mg','Saccharomyces boulardii'),
(null,'Bifilac','Cap',null,'Lactobacillus + Streptococcus faecalis'),
(null,'Vizylac','Cap',null,'Lactic Acid Bacillus'),
(null,'Zinc Sulphate','Syr','20 mg/5ml','Zinc Sulphate'),
(null,'Ursodeoxycholic Acid','Tab','300 mg','Ursodeoxycholic Acid'),
(null,'Silymarin','Tab','140 mg','Silymarin'),
(null,'L-Ornithine L-Aspartate','Sachet','3 g','L-Ornithine L-Aspartate'),

-- ── Antihistamines / Cold ─────────────────────────────────────────────────
(null,'Cetirizine','Syr','5 mg/5ml','Cetirizine'),
(null,'Cetirizine','Drops','2.5 mg/ml','Cetirizine'),
(null,'Levocetirizine','Syr','2.5 mg/5ml','Levocetirizine'),
(null,'Fexofenadine','Tab','180 mg','Fexofenadine'),
(null,'Allegra','Tab','120 mg','Fexofenadine'),
(null,'Bilastine','Tab','20 mg','Bilastine'),
(null,'Ebastine','Tab','10 mg','Ebastine'),
(null,'Rupatadine','Tab','10 mg','Rupatadine'),
(null,'Desloratadine','Tab','5 mg','Desloratadine'),
(null,'Loratadine','Tab','10 mg','Loratadine'),
(null,'Hydroxyzine','Tab','25 mg','Hydroxyzine'),
(null,'Pheniramine','Inj','22.75 mg/ml','Pheniramine Maleate'),
(null,'Avil','Tab','25 mg','Pheniramine Maleate'),
(null,'Montelukast + Fexofenadine','Tab','10/120 mg','Montelukast + Fexofenadine'),
(null,'Montair-LC','Tab','10/5 mg','Montelukast + Levocetirizine'),
(null,'Phenylephrine + Chlorpheniramine + Paracetamol','Tab','5/2/325 mg','Phenylephrine + Chlorpheniramine + Paracetamol'),

-- ── Respiratory ───────────────────────────────────────────────────────────
(null,'Salbutamol','Tab','2 mg','Salbutamol'),
(null,'Salbutamol','Respule','2.5 mg/2.5ml','Salbutamol'),
(null,'Levosalbutamol','Respule','1.25 mg/2.5ml','Levosalbutamol'),
(null,'Ipratropium + Levosalbutamol','Respule','500/1250 mcg','Ipratropium Bromide + Levosalbutamol'),
(null,'Duolin','Respule','500/1250 mcg','Ipratropium Bromide + Levosalbutamol'),
(null,'Budecort','Respule','0.5 mg/2ml','Budesonide'),
(null,'Budesonide + Formoterol','Inhaler','200/6 mcg','Budesonide + Formoterol'),
(null,'Foracort','Inhaler','200/6 mcg','Budesonide + Formoterol'),
(null,'Fluticasone + Salmeterol','Inhaler','250/25 mcg','Fluticasone + Salmeterol'),
(null,'Seroflo','Inhaler','250/25 mcg','Fluticasone + Salmeterol'),
(null,'Tiotropium','Inhaler','9 mcg','Tiotropium Bromide'),
(null,'Doxofylline','Tab','400 mg','Doxofylline'),
(null,'Acebrophylline','Cap','100 mg','Acebrophylline'),
(null,'Acetylcysteine','Sachet','600 mg','Acetylcysteine'),
(null,'Ambroxol','Tab','30 mg','Ambroxol'),
(null,'Guaifenesin','Syr','100 mg/5ml','Guaifenesin'),
(null,'Terbutaline + Bromhexine + Guaifenesin','Syr',null,'Terbutaline + Bromhexine + Guaifenesin'),
(null,'Ascoril LS','Syr',null,'Ambroxol + Guaifenesin + Levosalbutamol'),
(null,'Benadryl','Syr',null,'Diphenhydramine + Ammonium Chloride'),
(null,'Chericof','Syr',null,'Chlorpheniramine + Dextromethorphan + Paracetamol'),
(null,'Levodropropizine','Syr','30 mg/5ml','Levodropropizine'),

-- ── Antidiabetics ─────────────────────────────────────────────────────────
(null,'Metformin','Tab','850 mg','Metformin'),
(null,'Metformin SR','Tab','500 mg','Metformin'),
(null,'Metformin SR','Tab','1000 mg','Metformin'),
(null,'Glycomet','Tab','500 mg','Metformin'),
(null,'Glycomet-GP 1','Tab','1/500 mg','Glimepiride + Metformin'),
(null,'Glimepiride','Tab','2 mg','Glimepiride'),
(null,'Glimepiride','Tab','3 mg','Glimepiride'),
(null,'Glimepiride','Tab','4 mg','Glimepiride'),
(null,'Glipizide','Tab','5 mg','Glipizide'),
(null,'Gliclazide MR','Tab','60 mg','Gliclazide'),
(null,'Glibenclamide','Tab','5 mg','Glibenclamide'),
(null,'Sitagliptin + Metformin','Tab','50/500 mg','Sitagliptin + Metformin'),
(null,'Januvia','Tab','100 mg','Sitagliptin'),
(null,'Vildagliptin + Metformin','Tab','50/500 mg','Vildagliptin + Metformin'),
(null,'Galvus','Tab','50 mg','Vildagliptin'),
(null,'Linagliptin','Tab','5 mg','Linagliptin'),
(null,'Teneligliptin + Metformin','Tab','20/500 mg','Teneligliptin + Metformin'),
(null,'Dapagliflozin','Tab','10 mg','Dapagliflozin'),
(null,'Dapagliflozin + Metformin','Tab','10/500 mg','Dapagliflozin + Metformin'),
(null,'Empagliflozin','Tab','10 mg','Empagliflozin'),
(null,'Empagliflozin','Tab','25 mg','Empagliflozin'),
(null,'Pioglitazone','Tab','15 mg','Pioglitazone'),
(null,'Voglibose','Tab','0.3 mg','Voglibose'),
(null,'Acarbose','Tab','50 mg','Acarbose'),
(null,'Repaglinide','Tab','1 mg','Repaglinide'),
(null,'Insulin Glargine','Inj','100 IU/ml','Insulin Glargine'),
(null,'Lantus','Inj','100 IU/ml','Insulin Glargine'),
(null,'Insulin Aspart','Inj','100 IU/ml','Insulin Aspart'),
(null,'Insulin Lispro','Inj','100 IU/ml','Insulin Lispro'),
(null,'Human Actrapid','Inj','100 IU/ml','Insulin Human (Regular)'),
(null,'Huminsulin 30/70','Inj','100 IU/ml','Insulin Human (Biphasic)'),
(null,'Liraglutide','Inj','6 mg/ml','Liraglutide'),

-- ── Cardiovascular ────────────────────────────────────────────────────────
(null,'Amlodipine','Tab','2.5 mg','Amlodipine'),
(null,'Amlodipine','Tab','10 mg','Amlodipine'),
(null,'Amlodipine + Atenolol','Tab','5/50 mg','Amlodipine + Atenolol'),
(null,'Amlong','Tab','5 mg','Amlodipine'),
(null,'Cilnidipine','Tab','10 mg','Cilnidipine'),
(null,'Nifedipine','Tab','20 mg','Nifedipine'),
(null,'Telmisartan','Tab','20 mg','Telmisartan'),
(null,'Telmisartan','Tab','80 mg','Telmisartan'),
(null,'Telmisartan + Hydrochlorothiazide','Tab','40/12.5 mg','Telmisartan + Hydrochlorothiazide'),
(null,'Telmisartan + Metoprolol','Tab','40/25 mg','Telmisartan + Metoprolol'),
(null,'Telma','Tab','40 mg','Telmisartan'),
(null,'Telma-AM','Tab','40/5 mg','Telmisartan + Amlodipine'),
(null,'Olmesartan','Tab','20 mg','Olmesartan'),
(null,'Olmesartan + Amlodipine','Tab','20/5 mg','Olmesartan + Amlodipine'),
(null,'Losartan + Hydrochlorothiazide','Tab','50/12.5 mg','Losartan + Hydrochlorothiazide'),
(null,'Valsartan','Tab','80 mg','Valsartan'),
(null,'Sacubitril + Valsartan','Tab','50 mg','Sacubitril + Valsartan'),
(null,'Ramipril','Tab','2.5 mg','Ramipril'),
(null,'Ramipril','Tab','10 mg','Ramipril'),
(null,'Lisinopril','Tab','5 mg','Lisinopril'),
(null,'Perindopril','Tab','4 mg','Perindopril'),
(null,'Metoprolol XL','Tab','25 mg','Metoprolol'),
(null,'Metoprolol XL','Tab','50 mg','Metoprolol'),
(null,'Bisoprolol','Tab','5 mg','Bisoprolol'),
(null,'Carvedilol','Tab','6.25 mg','Carvedilol'),
(null,'Propranolol','Tab','40 mg','Propranolol'),
(null,'Ivabradine','Tab','5 mg','Ivabradine'),
(null,'Torsemide','Tab','10 mg','Torsemide'),
(null,'Spironolactone','Tab','25 mg','Spironolactone'),
(null,'Spironolactone + Furosemide','Tab','50/20 mg','Spironolactone + Furosemide'),
(null,'Chlorthalidone','Tab','12.5 mg','Chlorthalidone'),
(null,'Atorvastatin','Tab','20 mg','Atorvastatin'),
(null,'Atorvastatin','Tab','40 mg','Atorvastatin'),
(null,'Atorva','Tab','10 mg','Atorvastatin'),
(null,'Rosuvastatin','Tab','5 mg','Rosuvastatin'),
(null,'Rosuvastatin','Tab','20 mg','Rosuvastatin'),
(null,'Rosuvas','Tab','10 mg','Rosuvastatin'),
(null,'Simvastatin','Tab','20 mg','Simvastatin'),
(null,'Fenofibrate','Tab','160 mg','Fenofibrate'),
(null,'Ezetimibe','Tab','10 mg','Ezetimibe'),
(null,'Clopidogrel + Aspirin','Tab','75/75 mg','Clopidogrel + Aspirin'),
(null,'Ticagrelor','Tab','90 mg','Ticagrelor'),
(null,'Prasugrel','Tab','10 mg','Prasugrel'),
(null,'Warfarin','Tab','5 mg','Warfarin'),
(null,'Acitrom','Tab','2 mg','Acenocoumarol'),
(null,'Dabigatran','Cap','110 mg','Dabigatran'),
(null,'Rivaroxaban','Tab','10 mg','Rivaroxaban'),
(null,'Rivaroxaban','Tab','20 mg','Rivaroxaban'),
(null,'Apixaban','Tab','5 mg','Apixaban'),
(null,'Enoxaparin','Inj','40 mg','Enoxaparin'),
(null,'Isosorbide Mononitrate','Tab','20 mg','Isosorbide Mononitrate'),
(null,'Nitroglycerin','Tab','0.5 mg','Nitroglycerin'),
(null,'Sorbitrate','Tab','5 mg','Isosorbide Dinitrate'),
(null,'Digoxin','Tab','0.25 mg','Digoxin'),
(null,'Amiodarone','Tab','200 mg','Amiodarone'),
(null,'Trimetazidine','Tab','35 mg','Trimetazidine'),

-- ── Thyroid / Endocrine ───────────────────────────────────────────────────
(null,'Levothyroxine','Tab','25 mcg','Levothyroxine'),
(null,'Levothyroxine','Tab','75 mcg','Levothyroxine'),
(null,'Levothyroxine','Tab','100 mcg','Levothyroxine'),
(null,'Levothyroxine','Tab','12.5 mcg','Levothyroxine'),
(null,'Thyronorm','Tab','25 mcg','Levothyroxine'),
(null,'Thyronorm','Tab','100 mcg','Levothyroxine'),
(null,'Eltroxin','Tab','50 mcg','Levothyroxine'),
(null,'Carbimazole','Tab','5 mg','Carbimazole'),
(null,'Methimazole','Tab','5 mg','Methimazole'),
(null,'Propylthiouracil','Tab','50 mg','Propylthiouracil'),
(null,'Cabergoline','Tab','0.5 mg','Cabergoline'),

-- ── Vitamins / Supplements ────────────────────────────────────────────────
(null,'Cholecalciferol','Sachet','60000 IU','Cholecalciferol'),
(null,'Cholecalciferol','Tab','2000 IU','Cholecalciferol'),
(null,'Calcirol','Sachet','60000 IU','Cholecalciferol'),
(null,'Calcium Carbonate + Cholecalciferol','Tab','500/250 IU','Calcium Carbonate + Cholecalciferol'),
(null,'Calcium Citrate + Vitamin D3 + Zinc','Tab',null,'Calcium Citrate + Cholecalciferol + Zinc'),
(null,'Ferrous Sulphate','Tab','200 mg','Ferrous Sulphate'),
(null,'Ferrous Fumarate + Folic Acid','Tab',null,'Ferrous Fumarate + Folic Acid'),
(null,'Carbonyl Iron + Folic Acid + Zinc','Cap',null,'Carbonyl Iron + Folic Acid + Zinc'),
(null,'Iron Sucrose','Inj','20 mg/ml','Iron Sucrose'),
(null,'Folic Acid','Tab','1 mg','Folic Acid'),
(null,'Methylcobalamin','Inj','1000 mcg','Methylcobalamin'),
(null,'Methylcobalamin + Pregabalin','Cap','750/75 mcg','Methylcobalamin + Pregabalin'),
(null,'Vitamin B12','Tab','500 mcg','Cyanocobalamin'),
(null,'Neurobion Forte','Tab',null,'B-Complex Vitamins'),
(null,'Thiamine','Tab','100 mg','Thiamine'),
(null,'Ascorbic Acid','Tab','1000 mg','Ascorbic Acid'),
(null,'Zinc + Vitamin C','Tab',null,'Zinc + Ascorbic Acid'),
(null,'Omega-3 Fatty Acids','Cap','1000 mg','Omega-3 Fatty Acids'),
(null,'Protein Powder','Powder',null,'Protein Supplement'),
(null,'Magnesium','Tab','250 mg','Magnesium'),
(null,'Potassium Chloride','Tab','600 mg','Potassium Chloride'),
(null,'Potassium Chloride','Syr',null,'Potassium Chloride'),

-- ── Steroids ──────────────────────────────────────────────────────────────
(null,'Prednisolone','Tab','5 mg','Prednisolone'),
(null,'Prednisolone','Tab','20 mg','Prednisolone'),
(null,'Prednisolone','Syr','5 mg/5ml','Prednisolone'),
(null,'Wysolone','Tab','10 mg','Prednisolone'),
(null,'Methylprednisolone','Tab','8 mg','Methylprednisolone'),
(null,'Methylprednisolone','Inj','40 mg','Methylprednisolone'),
(null,'Deflazacort','Tab','30 mg','Deflazacort'),
(null,'Dexamethasone','Inj','4 mg/ml','Dexamethasone'),
(null,'Hydrocortisone','Inj','100 mg','Hydrocortisone'),
(null,'Fludrocortisone','Tab','0.1 mg','Fludrocortisone'),

-- ── Dermatology (topical) ─────────────────────────────────────────────────
(null,'Mometasone','Cream','0.1%','Mometasone'),
(null,'Clobetasol','Cream','0.05%','Clobetasol Propionate'),
(null,'Betamethasone + Neomycin','Cream',null,'Betamethasone + Neomycin'),
(null,'Fusidic Acid','Cream','2%','Fusidic Acid'),
(null,'Neosporin','Ointment',null,'Neomycin + Polymyxin B + Bacitracin'),
(null,'Luliconazole','Cream','1%','Luliconazole'),
(null,'Sertaconazole','Cream','2%','Sertaconazole'),
(null,'Terbinafine','Cream','1%','Terbinafine'),
(null,'Miconazole','Cream','2%','Miconazole'),
(null,'Permethrin','Cream','5%','Permethrin'),
(null,'Benzyl Benzoate','Lotion','25%','Benzyl Benzoate'),
(null,'Ivermectin','Lotion','1%','Ivermectin'),
(null,'Adapalene','Gel','0.1%','Adapalene'),
(null,'Adapalene + Benzoyl Peroxide','Gel','0.1/2.5%','Adapalene + Benzoyl Peroxide'),
(null,'Clindamycin','Gel','1%','Clindamycin'),
(null,'Benzoyl Peroxide','Gel','2.5%','Benzoyl Peroxide'),
(null,'Tacrolimus','Ointment','0.1%','Tacrolimus'),
(null,'Salicylic Acid','Ointment','6%','Salicylic Acid'),
(null,'Ketoconazole','Shampoo','2%','Ketoconazole'),
(null,'Minoxidil','Solution','5%','Minoxidil'),
(null,'Calamine','Lotion',null,'Calamine'),
(null,'Liquid Paraffin + White Soft Paraffin','Cream',null,'Liquid Paraffin + White Soft Paraffin'),
(null,'Povidone Iodine','Ointment','5%','Povidone Iodine'),
(null,'Silver Sulfadiazine','Cream','1%','Silver Sulfadiazine'),

-- ── Musculoskeletal / Gout / Bone ─────────────────────────────────────────
(null,'Thiocolchicoside','Cap','8 mg','Thiocolchicoside'),
(null,'Tizanidine','Tab','2 mg','Tizanidine'),
(null,'Baclofen','Tab','10 mg','Baclofen'),
(null,'Chlorzoxazone + Paracetamol + Diclofenac','Tab','250/325/50 mg','Chlorzoxazone + Paracetamol + Diclofenac'),
(null,'Cyclobenzaprine','Tab','5 mg','Cyclobenzaprine'),
(null,'Febuxostat','Tab','40 mg','Febuxostat'),
(null,'Febuxostat','Tab','80 mg','Febuxostat'),
(null,'Allopurinol','Tab','100 mg','Allopurinol'),
(null,'Colchicine','Tab','0.5 mg','Colchicine'),
(null,'Alendronate','Tab','70 mg','Alendronate'),
(null,'Risedronate','Tab','35 mg','Risedronate'),
(null,'Teriparatide','Inj','20 mcg','Teriparatide'),
(null,'Methotrexate','Tab','7.5 mg','Methotrexate'),
(null,'Sulfasalazine','Tab','500 mg','Sulfasalazine'),
(null,'Leflunomide','Tab','10 mg','Leflunomide'),
(null,'Glucosamine + Chondroitin','Tab',null,'Glucosamine + Chondroitin'),

-- ── Neurology / Psychiatry ────────────────────────────────────────────────
(null,'Pregabalin','Cap','150 mg','Pregabalin'),
(null,'Pregabalin','Cap','50 mg','Pregabalin'),
(null,'Gabapentin','Cap','100 mg','Gabapentin'),
(null,'Duloxetine','Cap','30 mg','Duloxetine'),
(null,'Amitriptyline','Tab','25 mg','Amitriptyline'),
(null,'Nortriptyline','Tab','25 mg','Nortriptyline'),
(null,'Sertraline','Tab','50 mg','Sertraline'),
(null,'Escitalopram','Tab','10 mg','Escitalopram'),
(null,'Escitalopram','Tab','5 mg','Escitalopram'),
(null,'Fluoxetine','Cap','20 mg','Fluoxetine'),
(null,'Paroxetine','Tab','12.5 mg','Paroxetine'),
(null,'Venlafaxine','Tab','37.5 mg','Venlafaxine'),
(null,'Mirtazapine','Tab','15 mg','Mirtazapine'),
(null,'Bupropion','Tab','150 mg','Bupropion'),
(null,'Alprazolam','Tab','0.25 mg','Alprazolam'),
(null,'Alprazolam','Tab','0.5 mg','Alprazolam'),
(null,'Clonazepam','Tab','0.5 mg','Clonazepam'),
(null,'Lorazepam','Tab','1 mg','Lorazepam'),
(null,'Diazepam','Tab','5 mg','Diazepam'),
(null,'Etizolam','Tab','0.5 mg','Etizolam'),
(null,'Zolpidem','Tab','5 mg','Zolpidem'),
(null,'Melatonin','Tab','3 mg','Melatonin'),
(null,'Quetiapine','Tab','25 mg','Quetiapine'),
(null,'Olanzapine','Tab','5 mg','Olanzapine'),
(null,'Risperidone','Tab','2 mg','Risperidone'),
(null,'Aripiprazole','Tab','10 mg','Aripiprazole'),
(null,'Haloperidol','Tab','5 mg','Haloperidol'),
(null,'Lithium Carbonate','Tab','300 mg','Lithium Carbonate'),
(null,'Sodium Valproate','Tab','500 mg','Sodium Valproate'),
(null,'Divalproex','Tab','500 mg','Divalproex Sodium'),
(null,'Levetiracetam','Tab','500 mg','Levetiracetam'),
(null,'Levetiracetam','Syr','100 mg/ml','Levetiracetam'),
(null,'Carbamazepine','Tab','200 mg','Carbamazepine'),
(null,'Oxcarbazepine','Tab','300 mg','Oxcarbazepine'),
(null,'Phenytoin','Tab','100 mg','Phenytoin'),
(null,'Lamotrigine','Tab','25 mg','Lamotrigine'),
(null,'Clobazam','Tab','5 mg','Clobazam'),
(null,'Topiramate','Tab','25 mg','Topiramate'),
(null,'Sumatriptan','Tab','50 mg','Sumatriptan'),
(null,'Rizatriptan','Tab','10 mg','Rizatriptan'),
(null,'Naratriptan','Tab','2.5 mg','Naratriptan'),
(null,'Flunarizine','Tab','10 mg','Flunarizine'),
(null,'Betahistine','Tab','16 mg','Betahistine'),
(null,'Vertin','Tab','16 mg','Betahistine'),
(null,'Prochlorperazine','Tab','5 mg','Prochlorperazine'),
(null,'Cinnarizine','Tab','25 mg','Cinnarizine'),
(null,'Donepezil','Tab','5 mg','Donepezil'),
(null,'Memantine','Tab','10 mg','Memantine'),
(null,'Levodopa + Carbidopa','Tab','100/25 mg','Levodopa + Carbidopa'),
(null,'Pramipexole','Tab','0.25 mg','Pramipexole'),
(null,'Trihexyphenidyl','Tab','2 mg','Trihexyphenidyl'),
(null,'Citicoline','Tab','500 mg','Citicoline'),

-- ── Urology / Nephrology ──────────────────────────────────────────────────
(null,'Tamsulosin','Tab','0.4 mg','Tamsulosin'),
(null,'Tamsulosin + Dutasteride','Tab','0.4/0.5 mg','Tamsulosin + Dutasteride'),
(null,'Silodosin','Cap','8 mg','Silodosin'),
(null,'Alfuzosin','Tab','10 mg','Alfuzosin'),
(null,'Finasteride','Tab','5 mg','Finasteride'),
(null,'Dutasteride','Cap','0.5 mg','Dutasteride'),
(null,'Solifenacin','Tab','5 mg','Solifenacin'),
(null,'Mirabegron','Tab','25 mg','Mirabegron'),
(null,'Tolterodine','Tab','2 mg','Tolterodine'),
(null,'Oxybutynin','Tab','5 mg','Oxybutynin'),
(null,'Sildenafil','Tab','50 mg','Sildenafil'),
(null,'Tadalafil','Tab','10 mg','Tadalafil'),
(null,'Potassium Citrate','Syr',null,'Potassium Citrate'),
(null,'Alkaline Citrate','Syr',null,'Disodium Hydrogen Citrate'),
(null,'Sevelamer','Tab','400 mg','Sevelamer'),
(null,'Cinacalcet','Tab','30 mg','Cinacalcet'),

-- ── Gynaecology / Obstetrics ──────────────────────────────────────────────
(null,'Ethinylestradiol + Levonorgestrel','Tab',null,'Ethinylestradiol + Levonorgestrel'),
(null,'Levonorgestrel','Tab','1.5 mg','Levonorgestrel'),
(null,'Medroxyprogesterone','Tab','10 mg','Medroxyprogesterone Acetate'),
(null,'Norethisterone','Tab','5 mg','Norethisterone'),
(null,'Progesterone','Cap','200 mg','Progesterone'),
(null,'Dydrogesterone','Tab','10 mg','Dydrogesterone'),
(null,'Duphaston','Tab','10 mg','Dydrogesterone'),
(null,'Tranexamic Acid','Tab','500 mg','Tranexamic Acid'),
(null,'Tranexamic Acid + Mefenamic Acid','Tab','500/250 mg','Tranexamic Acid + Mefenamic Acid'),
(null,'Letrozole','Tab','2.5 mg','Letrozole'),
(null,'Clomiphene Citrate','Tab','50 mg','Clomiphene Citrate'),
(null,'Myo-Inositol','Sachet',null,'Myo-Inositol'),
(null,'Iron + Folic Acid + Calcium','Tab',null,'Ferrous Fumarate + Folic Acid + Calcium'),
(null,'Clotrimazole','Pessary','500 mg','Clotrimazole'),
(null,'Estradiol','Tab','2 mg','Estradiol'),
(null,'Ubiquinol','Cap','100 mg','Ubiquinol'),

-- ── Ophthalmic / ENT ──────────────────────────────────────────────────────
(null,'Carboxymethylcellulose Eye Drops','Drops','0.5%','Carboxymethylcellulose'),
(null,'Sodium Hyaluronate Eye Drops','Drops','0.1%','Sodium Hyaluronate'),
(null,'Refresh Tears','Drops','0.5%','Carboxymethylcellulose'),
(null,'Tobramycin Eye Drops','Drops','0.3%','Tobramycin'),
(null,'Tobramycin + Dexamethasone Eye Drops','Drops',null,'Tobramycin + Dexamethasone'),
(null,'Gatifloxacin Eye Drops','Drops','0.3%','Gatifloxacin'),
(null,'Prednisolone Acetate Eye Drops','Drops','1%','Prednisolone Acetate'),
(null,'Olopatadine Eye Drops','Drops','0.1%','Olopatadine'),
(null,'Timolol Eye Drops','Drops','0.5%','Timolol'),
(null,'Latanoprost Eye Drops','Drops','0.005%','Latanoprost'),
(null,'Brimonidine Eye Drops','Drops','0.2%','Brimonidine'),
(null,'Ofloxacin Ear Drops','Drops','0.3%','Ofloxacin'),
(null,'Clotrimazole Ear Drops','Drops','1%','Clotrimazole'),
(null,'Paradichlorobenzene Ear Drops','Drops',null,'Paradichlorobenzene + Chlorbutol + Turpentine Oil'),
(null,'Fluticasone Nasal Spray','Nasal Spray','50 mcg','Fluticasone'),
(null,'Mometasone Nasal Spray','Nasal Spray','50 mcg','Mometasone'),
(null,'Nasoclear','Nasal Spray','0.65%','Sodium Chloride'),
(null,'Chlorhexidine Mouthwash','Mouthwash','0.2%','Chlorhexidine'),
(null,'Benzydamine Mouthwash','Mouthwash','0.15%','Benzydamine'),

-- ── Vaccines / Immunologicals (commonly stocked) ──────────────────────────
(null,'Tetanus Toxoid','Inj','0.5 ml','Tetanus Toxoid'),
(null,'Anti-Rabies Vaccine','Inj',null,'Rabies Vaccine'),
(null,'Hepatitis B Vaccine','Inj',null,'Hepatitis B Surface Antigen'),
(null,'Influenza Vaccine','Inj','0.5 ml','Influenza Vaccine'),
(null,'Typhoid Vaccine','Inj','0.5 ml','Typhoid Vi Polysaccharide'),

-- ── Miscellaneous / Emergency ─────────────────────────────────────────────
(null,'Adrenaline','Inj','1 mg/ml','Adrenaline'),
(null,'Atropine','Inj','0.6 mg/ml','Atropine'),
(null,'Normal Saline','IV Fluid','0.9%','Sodium Chloride'),
(null,'Ringer Lactate','IV Fluid',null,'Compound Sodium Lactate'),
(null,'Dextrose','IV Fluid','5%','Dextrose'),
(null,'Dextrose Normal Saline','IV Fluid',null,'Dextrose + Sodium Chloride'),
(null,'Oral Rehydration Salts','Sachet',null,'Oral Rehydration Salts'),
(null,'Activated Charcoal','Powder',null,'Activated Charcoal'),
(null,'Lignocaine','Inj','2%','Lignocaine'),
(null,'Lignocaine','Gel','2%','Lignocaine'),
(null,'Hydrogen Peroxide','Solution','6%','Hydrogen Peroxide'),
(null,'Povidone Iodine','Solution','5%','Povidone Iodine'),
(null,'Nicotine Gum','Gum','2 mg','Nicotine'),
(null,'Pilocarpine','Tab','5 mg','Pilocarpine'),
(null,'Deferasirox','Tab','500 mg','Deferasirox'),
(null,'Hydroxyurea','Cap','500 mg','Hydroxyurea')

on conflict do nothing;

-- ══════════════════════════════════════════════════════════════════════════
-- Batch 2: additional strengths of the generics above (dose titration is the
-- commonest reason a search misses), paediatric liquid forms, and further
-- well-known Indian brands.
-- ══════════════════════════════════════════════════════════════════════════

insert into medicines (clinic_id, name, form, strength, composition) values

-- ── Additional strengths: cardiovascular / metabolic ──────────────────────
(null,'Atorvastatin','Tab','80 mg','Atorvastatin'),
(null,'Rosuvastatin','Tab','40 mg','Rosuvastatin'),
(null,'Telmisartan','Tab','10 mg','Telmisartan'),
(null,'Olmesartan','Tab','40 mg','Olmesartan'),
(null,'Losartan','Tab','25 mg','Losartan'),
(null,'Losartan','Tab','100 mg','Losartan'),
(null,'Metoprolol','Tab','25 mg','Metoprolol'),
(null,'Metoprolol XL','Tab','100 mg','Metoprolol'),
(null,'Bisoprolol','Tab','2.5 mg','Bisoprolol'),
(null,'Carvedilol','Tab','3.125 mg','Carvedilol'),
(null,'Propranolol','Tab','20 mg','Propranolol'),
(null,'Atenolol','Tab','25 mg','Atenolol'),
(null,'Nebivolol','Tab','2.5 mg','Nebivolol'),
(null,'Ramipril','Tab','1.25 mg','Ramipril'),
(null,'Enalapril','Tab','2.5 mg','Enalapril'),
(null,'Enalapril','Tab','10 mg','Enalapril'),
(null,'Furosemide','Tab','20 mg','Furosemide'),
(null,'Torsemide','Tab','20 mg','Torsemide'),
(null,'Spironolactone','Tab','50 mg','Spironolactone'),
(null,'Hydrochlorothiazide','Tab','25 mg','Hydrochlorothiazide'),
(null,'Cilnidipine','Tab','5 mg','Cilnidipine'),
(null,'Clopidogrel','Tab','150 mg','Clopidogrel'),
(null,'Fenofibrate','Tab','145 mg','Fenofibrate'),
(null,'Isosorbide Mononitrate','Tab','30 mg','Isosorbide Mononitrate'),
(null,'Ivabradine','Tab','2.5 mg','Ivabradine'),

-- ── Additional strengths: diabetes ────────────────────────────────────────
(null,'Metformin SR','Tab','850 mg','Metformin'),
(null,'Glimepiride + Metformin','Tab','2/500 mg','Glimepiride + Metformin'),
(null,'Glimepiride + Metformin','Tab','1/1000 mg','Glimepiride + Metformin'),
(null,'Glimepiride + Metformin','Tab','2/1000 mg','Glimepiride + Metformin'),
(null,'Gliclazide','Tab','40 mg','Gliclazide'),
(null,'Gliclazide MR','Tab','30 mg','Gliclazide'),
(null,'Sitagliptin','Tab','50 mg','Sitagliptin'),
(null,'Sitagliptin + Metformin','Tab','50/1000 mg','Sitagliptin + Metformin'),
(null,'Vildagliptin','Tab','100 mg','Vildagliptin'),
(null,'Vildagliptin + Metformin','Tab','50/1000 mg','Vildagliptin + Metformin'),
(null,'Teneligliptin','Tab','10 mg','Teneligliptin'),
(null,'Dapagliflozin','Tab','5 mg','Dapagliflozin'),
(null,'Dapagliflozin + Metformin','Tab','10/1000 mg','Dapagliflozin + Metformin'),
(null,'Empagliflozin + Metformin','Tab','12.5/500 mg','Empagliflozin + Metformin'),
(null,'Pioglitazone','Tab','30 mg','Pioglitazone'),
(null,'Voglibose','Tab','0.2 mg','Voglibose'),
(null,'Insulin Glargine','Inj','300 IU/ml','Insulin Glargine'),
(null,'Insulin Degludec','Inj','100 IU/ml','Insulin Degludec'),

-- ── Additional strengths: antimicrobials ──────────────────────────────────
(null,'Amoxicillin','Cap','750 mg','Amoxicillin'),
(null,'Amoxicillin + Clavulanic Acid','Tab','375 mg','Amoxicillin + Clavulanic Acid'),
(null,'Azithromycin','Tab','1 g','Azithromycin'),
(null,'Azithromycin','Syr','100 mg/5ml','Azithromycin'),
(null,'Cefixime','Tab','400 mg','Cefixime'),
(null,'Cefixime','Syr','100 mg/5ml','Cefixime'),
(null,'Cefpodoxime','Syr','50 mg/5ml','Cefpodoxime'),
(null,'Cefuroxime','Tab','125 mg','Cefuroxime'),
(null,'Ceftriaxone','Inj','250 mg','Ceftriaxone'),
(null,'Ceftriaxone','Inj','500 mg','Ceftriaxone'),
(null,'Ciprofloxacin','Tab','750 mg','Ciprofloxacin'),
(null,'Doxycycline','Cap','50 mg','Doxycycline'),
(null,'Metronidazole','Inj','500 mg/100ml','Metronidazole'),
(null,'Ornidazole','Tab','250 mg','Ornidazole'),
(null,'Clindamycin','Cap','150 mg','Clindamycin'),
(null,'Fluconazole','Tab','50 mg','Fluconazole'),
(null,'Fluconazole','Tab','100 mg','Fluconazole'),
(null,'Itraconazole','Cap','65 mg','Itraconazole'),
(null,'Terbinafine','Tab','125 mg','Terbinafine'),
(null,'Acyclovir','Tab','200 mg','Acyclovir'),
(null,'Valacyclovir','Tab','1000 mg','Valacyclovir'),
(null,'Albendazole','Tab','200 mg','Albendazole'),
(null,'Hydroxychloroquine','Tab','400 mg','Hydroxychloroquine'),

-- ── Additional strengths: GI / respiratory / allergy ──────────────────────
(null,'Pantoprazole','Tab','80 mg','Pantoprazole'),
(null,'Omeprazole','Cap','10 mg','Omeprazole'),
(null,'Esomeprazole','Tab','20 mg','Esomeprazole'),
(null,'Rabeprazole','Tab','40 mg','Rabeprazole'),
(null,'Famotidine','Tab','20 mg','Famotidine'),
(null,'Domperidone','Tab','20 mg','Domperidone'),
(null,'Ondansetron','Tab','2 mg','Ondansetron'),
(null,'Loperamide','Cap','2 mg','Loperamide'),
(null,'Dicyclomine','Inj','10 mg/ml','Dicyclomine'),
(null,'Cetirizine','Tab','5 mg','Cetirizine'),
(null,'Levocetirizine','Tab','10 mg','Levocetirizine'),
(null,'Fexofenadine','Tab','30 mg','Fexofenadine'),
(null,'Fexofenadine','Syr','30 mg/5ml','Fexofenadine'),
(null,'Montelukast','Tab','4 mg','Montelukast'),
(null,'Montelukast','Tab','5 mg','Montelukast'),
(null,'Montelukast + Levocetirizine','Tab','4/2.5 mg','Montelukast + Levocetirizine'),
(null,'Budesonide','Inhaler','100 mcg','Budesonide'),
(null,'Budesonide','Inhaler','400 mcg','Budesonide'),
(null,'Budesonide + Formoterol','Inhaler','400/6 mcg','Budesonide + Formoterol'),
(null,'Fluticasone + Salmeterol','Inhaler','125/25 mcg','Fluticasone + Salmeterol'),
(null,'Salbutamol','Syr','2 mg/5ml','Salbutamol'),
(null,'Theophylline','Tab','300 mg','Theophylline'),
(null,'Doxofylline','Tab','200 mg','Doxofylline'),
(null,'Ambroxol','Syr','15 mg/5ml','Ambroxol'),

-- ── Paediatric liquid / low-dose forms ────────────────────────────────────
(null,'Ibuprofen','Susp','200 mg/5ml','Ibuprofen'),
(null,'Amoxicillin + Clavulanic Acid','Syr','156 mg/5ml','Amoxicillin + Clavulanic Acid'),
(null,'Amoxicillin + Clavulanic Acid','Syr','457 mg/5ml','Amoxicillin + Clavulanic Acid'),
(null,'Cefixime','Drops','25 mg/ml','Cefixime'),
(null,'Azithromycin','Susp','20 mg/ml','Azithromycin'),
(null,'Ofloxacin','Susp','50 mg/5ml','Ofloxacin'),
(null,'Domperidone','Drops','1 mg/ml','Domperidone'),
(null,'Ondansetron','Drops','2 mg/ml','Ondansetron'),
(null,'Cetirizine','Syr','2.5 mg/5ml','Cetirizine'),
(null,'Montelukast','Sachet','4 mg','Montelukast'),
(null,'Zinc Sulphate','Drops','10 mg/ml','Zinc Sulphate'),
(null,'Iron Drops','Drops',null,'Ferrous Sulphate'),
(null,'Multivitamin Drops','Drops',null,'Multivitamin'),
(null,'Vitamin D3 Drops','Drops','400 IU/ml','Cholecalciferol'),
(null,'Albendazole','Susp','400 mg/10ml','Albendazole'),
(null,'Paracetamol','Susp','125 mg/5ml','Paracetamol'),
(null,'Cefpodoxime + Clavulanic Acid','Syr','50/31.25 mg/5ml','Cefpodoxime + Clavulanic Acid'),
(null,'Prednisolone','Drops',null,'Prednisolone'),
(null,'Salbutamol','Respule','1.25 mg/2.5ml','Salbutamol'),
(null,'Budecort','Respule','0.25 mg/2ml','Budesonide'),

-- ── Further well-known Indian brands ──────────────────────────────────────
(null,'Dolo 650','Susp','250 mg/5ml','Paracetamol'),
(null,'Sumo','Tab',null,'Nimesulide + Paracetamol'),
(null,'Flexon','Tab',null,'Ibuprofen + Paracetamol'),
(null,'Disprin','Tab','325 mg','Aspirin'),
(null,'Saridon','Tab',null,'Paracetamol + Propyphenazone + Caffeine'),
(null,'Cyclopam','Tab',null,'Dicyclomine + Paracetamol'),
(null,'Spasmonil','Tab',null,'Dicyclomine + Paracetamol'),
(null,'Normaxin','Tab',null,'Chlordiazepoxide + Clidinium + Dicyclomine'),
(null,'Unienzyme','Tab',null,'Fungal Diastase + Papain + Activated Charcoal'),
(null,'Aristozyme','Syr',null,'Fungal Diastase + Pepsin'),
(null,'Zinetac','Tab','150 mg','Ranitidine'),
(null,'Aciloc','Tab','150 mg','Ranitidine'),
(null,'Ocid','Cap','20 mg','Omeprazole'),
(null,'Omez','Cap','20 mg','Omeprazole'),
(null,'Pantosec','Tab','40 mg','Pantoprazole'),
(null,'Vomikind','Tab','4 mg','Ondansetron'),
(null,'Perinorm','Tab','10 mg','Metoclopramide'),
(null,'Zofer','Tab','4 mg','Ondansetron'),
(null,'Cetzine','Tab','10 mg','Cetirizine'),
(null,'Alerid','Tab','10 mg','Cetirizine'),
(null,'Levocet','Tab','5 mg','Levocetirizine'),
(null,'Montek-LC','Tab','10/5 mg','Montelukast + Levocetirizine'),
(null,'Okacet','Tab','10 mg','Cetirizine'),
(null,'Nasivion','Nasal Drops','0.05%','Oxymetazoline'),
(null,'Sinarest Nasal','Nasal Drops','0.05%','Oxymetazoline'),
(null,'Betadine','Ointment','5%','Povidone Iodine'),
(null,'Soframycin','Cream','1%','Framycetin'),
(null,'Candid','Cream','1%','Clotrimazole'),
(null,'Candid-B','Cream',null,'Clotrimazole + Beclomethasone'),
(null,'Quadriderm','Cream',null,'Beclomethasone + Clotrimazole + Gentamicin'),
(null,'Panderm','Cream',null,'Clobetasol + Ofloxacin + Ornidazole + Terbinafine'),
(null,'Clop-G','Cream',null,'Clobetasol + Gentamicin'),
(null,'Elocon','Cream','0.1%','Mometasone'),
(null,'T-Bact','Ointment','2%','Mupirocin'),
(null,'Volini','Gel',null,'Diclofenac + Methyl Salicylate + Menthol'),
(null,'Moov','Cream',null,'Diclofenac + Methyl Salicylate + Menthol'),
(null,'Iodex','Ointment',null,'Methyl Salicylate + Menthol'),
(null,'Amrutanjan','Balm',null,'Menthol + Camphor + Eucalyptus Oil'),
(null,'Vicks VapoRub','Ointment',null,'Camphor + Menthol + Eucalyptus Oil'),
(null,'Otrivin','Nasal Drops','0.05%','Xylometazoline'),
(null,'Liv 52','Tab',null,'Herbal Hepatoprotective'),
(null,'Cypon','Syr',null,'Cyproheptadine + Tricholine Citrate'),
(null,'Practin','Tab','4 mg','Cyproheptadine'),
(null,'Dexorange','Syr',null,'Iron + Folic Acid + Vitamin B12'),
(null,'Autrin','Cap',null,'Ferrous Fumarate + Folic Acid + Vitamin B12'),
(null,'Orofer XT','Tab',null,'Ferrous Ascorbate + Folic Acid'),
(null,'Fefol','Cap',null,'Ferrous Sulphate + Folic Acid'),
(null,'Supradyn','Tab',null,'Multivitamin + Multimineral'),
(null,'A to Z','Tab',null,'Multivitamin + Multimineral'),
(null,'Revital','Cap',null,'Multivitamin + Ginseng'),
(null,'Calcimax','Tab',null,'Calcium Carbonate + Cholecalciferol'),
(null,'Gemcal','Cap',null,'Calcitriol + Calcium Carbonate'),
(null,'Calcitriol','Cap','0.25 mcg','Calcitriol'),
(null,'Uprise D3','Sachet','60000 IU','Cholecalciferol'),
(null,'Nurokind','Tab','1500 mcg','Methylcobalamin'),
(null,'Nurokind Plus','Cap',null,'Methylcobalamin + Alpha Lipoic Acid'),
(null,'Rejunex','Cap',null,'Methylcobalamin + Alpha Lipoic Acid'),
(null,'Pregabid','Cap','75 mg','Pregabalin'),
(null,'Gabapin','Cap','300 mg','Gabapentin'),
(null,'Nexito','Tab','10 mg','Escitalopram'),
(null,'Zoloft','Tab','50 mg','Sertraline'),
(null,'Restyl','Tab','0.5 mg','Alprazolam'),
(null,'Lonazep','Tab','0.5 mg','Clonazepam'),
(null,'Etilaam','Tab','0.5 mg','Etizolam'),
(null,'Zolfresh','Tab','10 mg','Zolpidem'),
(null,'Levipil','Tab','500 mg','Levetiracetam'),
(null,'Encorate','Tab','500 mg','Sodium Valproate'),
(null,'Eptoin','Tab','100 mg','Phenytoin'),
(null,'Sibelium','Tab','10 mg','Flunarizine'),
(null,'Stugeron','Tab','25 mg','Cinnarizine'),
(null,'Urimax','Cap','0.4 mg','Tamsulosin'),
(null,'Urimax-D','Tab','0.4/0.5 mg','Tamsulosin + Dutasteride'),
(null,'Veltam','Tab','0.4 mg','Tamsulosin'),
(null,'Zyloric','Tab','100 mg','Allopurinol'),
(null,'Febutaz','Tab','40 mg','Febuxostat'),
(null,'Zerodol-MR','Tab',null,'Aceclofenac + Paracetamol + Chlorzoxazone'),
(null,'Myoril','Cap','4 mg','Thiocolchicoside'),
(null,'Cetaphil','Lotion',null,'Emollient'),
(null,'Venusia','Cream',null,'Emollient'),
(null,'Moisturex','Cream',null,'Urea + Lactic Acid'),
(null,'Tugain','Solution','5%','Minoxidil'),
(null,'Nizral','Shampoo','2%','Ketoconazole'),
(null,'Scalpe','Shampoo',null,'Ketoconazole + Zinc Pyrithione'),
(null,'Clearz','Cream',null,'Kojic Acid + Arbutin'),
(null,'Melalite','Cream','4%','Hydroquinone'),
(null,'Systane','Drops',null,'Polyethylene Glycol + Propylene Glycol'),
(null,'Genteal','Drops',null,'Hypromellose'),
(null,'Milflox','Drops','0.5%','Moxifloxacin'),
(null,'Moxicip','Drops','0.5%','Moxifloxacin'),
(null,'Ciplox','Drops','0.3%','Ciprofloxacin'),
(null,'Toba','Drops','0.3%','Tobramycin'),
(null,'Pred Forte','Drops','1%','Prednisolone Acetate'),
(null,'Patanol','Drops','0.1%','Olopatadine'),
(null,'Xalatan','Drops','0.005%','Latanoprost'),
(null,'Duphalac','Syr','10 g/15ml','Lactulose'),
(null,'Looz','Syr','10 g/15ml','Lactulose'),
(null,'Softovac','Powder',null,'Ispaghula Husk + Senna'),
(null,'Naturolax','Powder',null,'Ispaghula Husk'),
(null,'Enterogermina','Susp',null,'Bacillus clausii'),
(null,'Sporlac','Tab',null,'Lactic Acid Bacillus'),
(null,'Darolac','Sachet',null,'Probiotic Blend'),
(null,'Electral','Sachet',null,'Oral Rehydration Salts'),
(null,'Walyte','Sachet',null,'Oral Rehydration Salts')

on conflict do nothing;
