-- v7 Wave 1: ICD-10 coded diagnoses.
--
-- This is ClinicFlow's first healthcare-standards foothold. Free-text diagnosis
-- can't be aggregated, exchanged, or mapped to a claim; a coded one can.
-- Coding is the technical prerequisite for FHIR export (Condition resources),
-- NHCX/insurance claims, and condition-level analytics — so this lands before
-- any of those.
--
-- `visits.diagnosis` is KEPT as free text and remains the primary field. Codes
-- are additive: a doctor who never touches the code picker loses nothing.
--
-- SCOPE: a CURATED subset (~350) of the codes an Indian OPD actually uses,
-- across all chapters. ICD-10 in full is ~70,000 codes; clinics needing the
-- complete set import it (Settings → Medicines → Import uses the same pipeline).

create table if not exists icd10_codes (
  code    text primary key,
  title   text not null,
  chapter text
);

alter table icd10_codes enable row level security;

-- A published reference standard: readable by any signed-in user, written only
-- by migrations/service role (no insert/update/delete policy exists).
drop policy if exists icd10_read on icd10_codes;
create policy icd10_read on icd10_codes for select to authenticated using (true);

create index if not exists icd10_title_trgm on icd10_codes using gin (title gin_trgm_ops);

alter table visits add column if not exists diagnosis_codes text[] not null default '{}';

insert into icd10_codes (code, title, chapter) values
-- Infectious and parasitic
('A01.0','Typhoid fever','Infectious'),
('A02.0','Salmonella enteritis','Infectious'),
('A03.9','Shigellosis, unspecified','Infectious'),
('A04.9','Bacterial intestinal infection, unspecified','Infectious'),
('A06.0','Acute amoebic dysentery','Infectious'),
('A08.4','Viral intestinal infection, unspecified','Infectious'),
('A09','Diarrhoea and gastroenteritis of presumed infectious origin','Infectious'),
('A15.0','Tuberculosis of lung, confirmed by sputum microscopy','Infectious'),
('A15.9','Respiratory tuberculosis, confirmed, unspecified','Infectious'),
('A16.9','Respiratory tuberculosis, not confirmed','Infectious'),
('A18.0','Tuberculosis of bones and joints','Infectious'),
('A27.9','Leptospirosis, unspecified','Infectious'),
('A30.9','Leprosy, unspecified','Infectious'),
('A37.9','Whooping cough, unspecified','Infectious'),
('A39.0','Meningococcal meningitis','Infectious'),
('A41.9','Sepsis, unspecified','Infectious'),
('A46','Erysipelas','Infectious'),
('A49.9','Bacterial infection, unspecified','Infectious'),
('A54.9','Gonococcal infection, unspecified','Infectious'),
('A59.9','Trichomoniasis, unspecified','Infectious'),
('A63.0','Anogenital warts','Infectious'),
('A64','Unspecified sexually transmitted disease','Infectious'),
('A77.1','Spotted fever due to Rickettsia conorii','Infectious'),
('A90','Dengue fever','Infectious'),
('A91','Dengue haemorrhagic fever','Infectious'),
('A92.0','Chikungunya virus disease','Infectious'),
('B01.9','Varicella without complication','Infectious'),
('B02.9','Zoster without complication','Infectious'),
('B05.9','Measles without complication','Infectious'),
('B15.9','Hepatitis A without hepatic coma','Infectious'),
('B16.9','Acute hepatitis B without hepatic coma','Infectious'),
('B17.1','Acute hepatitis C','Infectious'),
('B18.1','Chronic viral hepatitis B','Infectious'),
('B18.2','Chronic viral hepatitis C','Infectious'),
('B19.9','Unspecified viral hepatitis without hepatic coma','Infectious'),
('B24','Unspecified HIV disease','Infectious'),
('B26.9','Mumps without complication','Infectious'),
('B27.9','Infectious mononucleosis, unspecified','Infectious'),
('B34.9','Viral infection, unspecified','Infectious'),
('B35.0','Tinea barbae and tinea capitis','Infectious'),
('B35.1','Tinea unguium','Infectious'),
('B35.3','Tinea pedis','Infectious'),
('B35.4','Tinea corporis','Infectious'),
('B35.6','Tinea cruris','Infectious'),
('B35.9','Dermatophytosis, unspecified','Infectious'),
('B36.0','Pityriasis versicolor','Infectious'),
('B37.0','Candidal stomatitis','Infectious'),
('B37.3','Candidiasis of vulva and vagina','Infectious'),
('B37.9','Candidiasis, unspecified','Infectious'),
('B50.9','Plasmodium falciparum malaria, unspecified','Infectious'),
('B51.9','Plasmodium vivax malaria without complication','Infectious'),
('B54','Unspecified malaria','Infectious'),
('B76.9','Hookworm disease, unspecified','Infectious'),
('B77.9','Ascariasis without complications','Infectious'),
('B80','Enterobiasis','Infectious'),
('B82.9','Intestinal parasitism, unspecified','Infectious'),
('B86','Scabies','Infectious'),
('B99','Other and unspecified infectious diseases','Infectious'),

-- Neoplasms
('C34.9','Malignant neoplasm of bronchus or lung, unspecified','Neoplasms'),
('C50.9','Malignant neoplasm of breast, unspecified','Neoplasms'),
('D17.9','Benign lipomatous neoplasm, unspecified','Neoplasms'),
('D18.0','Haemangioma, any site','Neoplasms'),
('D22.9','Melanocytic naevi, unspecified','Neoplasms'),
('D24','Benign neoplasm of breast','Neoplasms'),
('D25.9','Leiomyoma of uterus, unspecified','Neoplasms'),

-- Blood
('D50.9','Iron deficiency anaemia, unspecified','Blood'),
('D51.9','Vitamin B12 deficiency anaemia, unspecified','Blood'),
('D52.9','Folate deficiency anaemia, unspecified','Blood'),
('D53.9','Nutritional anaemia, unspecified','Blood'),
('D56.1','Beta thalassaemia','Blood'),
('D57.1','Sickle-cell disease without crisis','Blood'),
('D58.9','Hereditary haemolytic anaemia, unspecified','Blood'),
('D64.9','Anaemia, unspecified','Blood'),
('D69.3','Immune thrombocytopenic purpura','Blood'),
('D69.6','Thrombocytopenia, unspecified','Blood'),

-- Endocrine, nutritional and metabolic
('E03.9','Hypothyroidism, unspecified','Endocrine'),
('E04.9','Nontoxic goitre, unspecified','Endocrine'),
('E05.9','Thyrotoxicosis, unspecified','Endocrine'),
('E06.3','Autoimmune thyroiditis','Endocrine'),
('E10.9','Type 1 diabetes mellitus without complications','Endocrine'),
('E11.2','Type 2 diabetes mellitus with kidney complications','Endocrine'),
('E11.3','Type 2 diabetes mellitus with ophthalmic complications','Endocrine'),
('E11.4','Type 2 diabetes mellitus with neurological complications','Endocrine'),
('E11.5','Type 2 diabetes mellitus with peripheral circulatory complications','Endocrine'),
('E11.6','Type 2 diabetes mellitus with other specified complications','Endocrine'),
('E11.7','Type 2 diabetes mellitus with multiple complications','Endocrine'),
('E11.9','Type 2 diabetes mellitus without complications','Endocrine'),
('E14.9','Unspecified diabetes mellitus without complications','Endocrine'),
('E16.2','Hypoglycaemia, unspecified','Endocrine'),
('E21.3','Hyperparathyroidism, unspecified','Endocrine'),
('E22.1','Hyperprolactinaemia','Endocrine'),
('E27.1','Primary adrenocortical insufficiency','Endocrine'),
('E28.2','Polycystic ovarian syndrome','Endocrine'),
('E44.1','Mild protein-energy malnutrition','Endocrine'),
('E46','Unspecified protein-energy malnutrition','Endocrine'),
('E50.9','Vitamin A deficiency, unspecified','Endocrine'),
('E53.8','Deficiency of other specified B group vitamins','Endocrine'),
('E55.9','Vitamin D deficiency, unspecified','Endocrine'),
('E56.9','Vitamin deficiency, unspecified','Endocrine'),
('E61.1','Iron deficiency','Endocrine'),
('E63.9','Nutritional deficiency, unspecified','Endocrine'),
('E66.9','Obesity, unspecified','Endocrine'),
('E78.0','Pure hypercholesterolaemia','Endocrine'),
('E78.1','Pure hyperglyceridaemia','Endocrine'),
('E78.2','Mixed hyperlipidaemia','Endocrine'),
('E78.5','Hyperlipidaemia, unspecified','Endocrine'),
('E79.0','Hyperuricaemia without arthritis','Endocrine'),
('E86','Volume depletion','Endocrine'),
('E87.1','Hypo-osmolality and hyponatraemia','Endocrine'),
('E87.5','Hyperkalaemia','Endocrine'),
('E87.6','Hypokalaemia','Endocrine'),

-- Mental and behavioural
('F10.1','Harmful use of alcohol','Mental'),
('F10.2','Alcohol dependence syndrome','Mental'),
('F17.2','Nicotine dependence','Mental'),
('F20.9','Schizophrenia, unspecified','Mental'),
('F31.9','Bipolar affective disorder, unspecified','Mental'),
('F32.0','Mild depressive episode','Mental'),
('F32.1','Moderate depressive episode','Mental'),
('F32.2','Severe depressive episode without psychotic symptoms','Mental'),
('F32.9','Depressive episode, unspecified','Mental'),
('F33.9','Recurrent depressive disorder, unspecified','Mental'),
('F40.1','Social phobias','Mental'),
('F41.0','Panic disorder','Mental'),
('F41.1','Generalised anxiety disorder','Mental'),
('F41.2','Mixed anxiety and depressive disorder','Mental'),
('F41.9','Anxiety disorder, unspecified','Mental'),
('F42.9','Obsessive-compulsive disorder, unspecified','Mental'),
('F43.0','Acute stress reaction','Mental'),
('F43.1','Post-traumatic stress disorder','Mental'),
('F43.2','Adjustment disorders','Mental'),
('F44.9','Dissociative disorder, unspecified','Mental'),
('F45.9','Somatoform disorder, unspecified','Mental'),
('F48.0','Neurasthenia','Mental'),
('F51.0','Nonorganic insomnia','Mental'),
('F70.9','Mild mental retardation','Mental'),
('F80.9','Developmental disorder of speech and language, unspecified','Mental'),
('F84.0','Childhood autism','Mental'),
('F90.0','Disturbance of activity and attention','Mental'),
('F99','Mental disorder, not otherwise specified','Mental'),

-- Nervous system
('G03.9','Meningitis, unspecified','Nervous'),
('G40.9','Epilepsy, unspecified','Nervous'),
('G41.9','Status epilepticus, unspecified','Nervous'),
('G43.9','Migraine, unspecified','Nervous'),
('G44.2','Tension-type headache','Nervous'),
('G45.9','Transient cerebral ischaemic attack, unspecified','Nervous'),
('G47.0','Insomnia','Nervous'),
('G47.3','Sleep apnoea','Nervous'),
('G50.0','Trigeminal neuralgia','Nervous'),
('G51.0','Bell palsy','Nervous'),
('G54.9','Nerve root and plexus disorder, unspecified','Nervous'),
('G56.0','Carpal tunnel syndrome','Nervous'),
('G57.9','Mononeuropathy of lower limb, unspecified','Nervous'),
('G62.9','Polyneuropathy, unspecified','Nervous'),
('G63.2','Diabetic polyneuropathy','Nervous'),
('G80.9','Cerebral palsy, unspecified','Nervous'),
('G81.9','Hemiplegia, unspecified','Nervous'),
('G93.9','Disorder of brain, unspecified','Nervous'),

-- Eye
('H00.0','Hordeolum','Eye'),
('H01.0','Blepharitis','Eye'),
('H10.1','Acute atopic conjunctivitis','Eye'),
('H10.9','Conjunctivitis, unspecified','Eye'),
('H11.0','Pterygium','Eye'),
('H16.9','Keratitis, unspecified','Eye'),
('H25.9','Senile cataract, unspecified','Eye'),
('H26.9','Cataract, unspecified','Eye'),
('H35.0','Background retinopathy','Eye'),
('H36.0','Diabetic retinopathy','Eye'),
('H40.9','Glaucoma, unspecified','Eye'),
('H52.0','Hypermetropia','Eye'),
('H52.1','Myopia','Eye'),
('H52.2','Astigmatism','Eye'),
('H52.4','Presbyopia','Eye'),
('H57.9','Disorder of eye and adnexa, unspecified','Eye'),

-- Ear
('H60.9','Otitis externa, unspecified','Ear'),
('H61.2','Impacted cerumen','Ear'),
('H65.9','Nonsuppurative otitis media, unspecified','Ear'),
('H66.9','Otitis media, unspecified','Ear'),
('H72.0','Central perforation of tympanic membrane','Ear'),
('H81.0','Meniere disease','Ear'),
('H81.1','Benign paroxysmal vertigo','Ear'),
('H81.3','Other peripheral vertigo','Ear'),
('H90.3','Sensorineural hearing loss, bilateral','Ear'),
('H91.9','Hearing loss, unspecified','Ear'),
('H92.0','Otalgia','Ear'),

-- Circulatory
('I10','Essential (primary) hypertension','Circulatory'),
('I11.9','Hypertensive heart disease without heart failure','Circulatory'),
('I12.9','Hypertensive renal disease without renal failure','Circulatory'),
('I15.9','Secondary hypertension, unspecified','Circulatory'),
('I20.0','Unstable angina','Circulatory'),
('I20.9','Angina pectoris, unspecified','Circulatory'),
('I21.9','Acute myocardial infarction, unspecified','Circulatory'),
('I25.1','Atherosclerotic heart disease','Circulatory'),
('I25.9','Chronic ischaemic heart disease, unspecified','Circulatory'),
('I34.0','Mitral valve insufficiency','Circulatory'),
('I42.0','Dilated cardiomyopathy','Circulatory'),
('I48.9','Atrial fibrillation and atrial flutter, unspecified','Circulatory'),
('I49.9','Cardiac arrhythmia, unspecified','Circulatory'),
('I50.9','Heart failure, unspecified','Circulatory'),
('I63.9','Cerebral infarction, unspecified','Circulatory'),
('I64','Stroke, not specified as haemorrhage or infarction','Circulatory'),
('I67.9','Cerebrovascular disease, unspecified','Circulatory'),
('I70.2','Atherosclerosis of arteries of extremities','Circulatory'),
('I73.9','Peripheral vascular disease, unspecified','Circulatory'),
('I83.9','Varicose veins of lower extremities','Circulatory'),
('I84.9','Unspecified haemorrhoids without complication','Circulatory'),
('I95.9','Hypotension, unspecified','Circulatory'),
('I99','Other and unspecified disorders of circulatory system','Circulatory'),

-- Respiratory
('J00','Acute nasopharyngitis (common cold)','Respiratory'),
('J01.9','Acute sinusitis, unspecified','Respiratory'),
('J02.9','Acute pharyngitis, unspecified','Respiratory'),
('J03.9','Acute tonsillitis, unspecified','Respiratory'),
('J04.0','Acute laryngitis','Respiratory'),
('J05.0','Acute obstructive laryngitis (croup)','Respiratory'),
('J06.9','Acute upper respiratory infection, unspecified','Respiratory'),
('J10.1','Influenza with respiratory manifestations, virus identified','Respiratory'),
('J11.1','Influenza with respiratory manifestations, virus not identified','Respiratory'),
('J12.9','Viral pneumonia, unspecified','Respiratory'),
('J15.9','Bacterial pneumonia, unspecified','Respiratory'),
('J18.9','Pneumonia, unspecified','Respiratory'),
('J20.9','Acute bronchitis, unspecified','Respiratory'),
('J21.9','Acute bronchiolitis, unspecified','Respiratory'),
('J22','Unspecified acute lower respiratory infection','Respiratory'),
('J30.1','Allergic rhinitis due to pollen','Respiratory'),
('J30.4','Allergic rhinitis, unspecified','Respiratory'),
('J31.0','Chronic rhinitis','Respiratory'),
('J32.9','Chronic sinusitis, unspecified','Respiratory'),
('J34.2','Deviated nasal septum','Respiratory'),
('J35.0','Chronic tonsillitis','Respiratory'),
('J35.1','Hypertrophy of tonsils','Respiratory'),
('J40','Bronchitis, not specified as acute or chronic','Respiratory'),
('J42','Unspecified chronic bronchitis','Respiratory'),
('J44.1','COPD with acute exacerbation','Respiratory'),
('J44.9','Chronic obstructive pulmonary disease, unspecified','Respiratory'),
('J45.0','Predominantly allergic asthma','Respiratory'),
('J45.9','Asthma, unspecified','Respiratory'),
('J46','Status asthmaticus','Respiratory'),
('J47','Bronchiectasis','Respiratory'),
('J90','Pleural effusion','Respiratory'),
('J93.9','Pneumothorax, unspecified','Respiratory'),
('J98.9','Respiratory disorder, unspecified','Respiratory'),

-- Digestive
('K02.9','Dental caries, unspecified','Digestive'),
('K05.1','Chronic gingivitis','Digestive'),
('K05.3','Chronic periodontitis','Digestive'),
('K08.9','Disorder of teeth and supporting structures, unspecified','Digestive'),
('K12.0','Recurrent oral aphthae','Digestive'),
('K12.1','Other forms of stomatitis','Digestive'),
('K13.0','Diseases of lips','Digestive'),
('K20','Oesophagitis','Digestive'),
('K21.0','Gastro-oesophageal reflux disease with oesophagitis','Digestive'),
('K21.9','Gastro-oesophageal reflux disease without oesophagitis','Digestive'),
('K25.9','Gastric ulcer, unspecified','Digestive'),
('K26.9','Duodenal ulcer, unspecified','Digestive'),
('K27.9','Peptic ulcer, site unspecified','Digestive'),
('K29.0','Acute haemorrhagic gastritis','Digestive'),
('K29.7','Gastritis, unspecified','Digestive'),
('K30','Dyspepsia','Digestive'),
('K35.8','Acute appendicitis, other and unspecified','Digestive'),
('K40.9','Unilateral inguinal hernia without obstruction','Digestive'),
('K42.9','Umbilical hernia without obstruction','Digestive'),
('K52.9','Noninfective gastroenteritis and colitis, unspecified','Digestive'),
('K57.9','Diverticular disease of intestine, unspecified','Digestive'),
('K58.9','Irritable bowel syndrome without diarrhoea','Digestive'),
('K59.0','Constipation','Digestive'),
('K59.1','Functional diarrhoea','Digestive'),
('K60.2','Anal fissure, unspecified','Digestive'),
('K61.0','Anal abscess','Digestive'),
('K62.5','Haemorrhage of anus and rectum','Digestive'),
('K64.9','Haemorrhoids, unspecified','Digestive'),
('K70.3','Alcoholic cirrhosis of liver','Digestive'),
('K73.9','Chronic hepatitis, unspecified','Digestive'),
('K74.6','Other and unspecified cirrhosis of liver','Digestive'),
('K75.9','Inflammatory liver disease, unspecified','Digestive'),
('K76.0','Fatty liver, not elsewhere classified','Digestive'),
('K80.2','Calculus of gallbladder without cholecystitis','Digestive'),
('K81.9','Cholecystitis, unspecified','Digestive'),
('K85.9','Acute pancreatitis, unspecified','Digestive'),
('K92.2','Gastrointestinal haemorrhage, unspecified','Digestive'),

-- Skin
('L01.0','Impetigo','Skin'),
('L02.9','Cutaneous abscess, furuncle and carbuncle, unspecified','Skin'),
('L03.9','Cellulitis, unspecified','Skin'),
('L08.9','Local infection of skin and subcutaneous tissue, unspecified','Skin'),
('L20.9','Atopic dermatitis, unspecified','Skin'),
('L21.9','Seborrhoeic dermatitis, unspecified','Skin'),
('L23.9','Allergic contact dermatitis, unspecified cause','Skin'),
('L24.9','Irritant contact dermatitis, unspecified cause','Skin'),
('L25.9','Unspecified contact dermatitis, unspecified cause','Skin'),
('L27.0','Generalized skin eruption due to drugs','Skin'),
('L28.0','Lichen simplex chronicus','Skin'),
('L29.9','Pruritus, unspecified','Skin'),
('L30.9','Dermatitis, unspecified','Skin'),
('L40.9','Psoriasis, unspecified','Skin'),
('L42','Pityriasis rosea','Skin'),
('L43.9','Lichen planus, unspecified','Skin'),
('L50.9','Urticaria, unspecified','Skin'),
('L60.0','Ingrowing nail','Skin'),
('L63.9','Alopecia areata, unspecified','Skin'),
('L64.9','Androgenic alopecia, unspecified','Skin'),
('L70.0','Acne vulgaris','Skin'),
('L71.9','Rosacea, unspecified','Skin'),
('L73.9','Follicular disorder, unspecified','Skin'),
('L80','Vitiligo','Skin'),
('L81.4','Other melanin hyperpigmentation','Skin'),
('L84','Corns and callosities','Skin'),
('L85.3','Xerosis cutis','Skin'),
('L98.9','Disorder of skin and subcutaneous tissue, unspecified','Skin'),

-- Musculoskeletal
('M05.9','Seropositive rheumatoid arthritis, unspecified','Musculoskeletal'),
('M06.9','Rheumatoid arthritis, unspecified','Musculoskeletal'),
('M10.9','Gout, unspecified','Musculoskeletal'),
('M13.9','Arthritis, unspecified','Musculoskeletal'),
('M15.9','Polyarthrosis, unspecified','Musculoskeletal'),
('M16.9','Coxarthrosis, unspecified','Musculoskeletal'),
('M17.9','Gonarthrosis, unspecified','Musculoskeletal'),
('M19.9','Arthrosis, unspecified','Musculoskeletal'),
('M23.9','Internal derangement of knee, unspecified','Musculoskeletal'),
('M25.5','Pain in joint','Musculoskeletal'),
('M32.9','Systemic lupus erythematosus, unspecified','Musculoskeletal'),
('M35.0','Sicca syndrome','Musculoskeletal'),
('M41.9','Scoliosis, unspecified','Musculoskeletal'),
('M45','Ankylosing spondylitis','Musculoskeletal'),
('M47.9','Spondylosis, unspecified','Musculoskeletal'),
('M48.0','Spinal stenosis','Musculoskeletal'),
('M50.1','Cervical disc disorder with radiculopathy','Musculoskeletal'),
('M51.1','Lumbar disc disorder with radiculopathy','Musculoskeletal'),
('M53.1','Cervicobrachial syndrome','Musculoskeletal'),
('M54.2','Cervicalgia','Musculoskeletal'),
('M54.3','Sciatica','Musculoskeletal'),
('M54.4','Lumbago with sciatica','Musculoskeletal'),
('M54.5','Low back pain','Musculoskeletal'),
('M54.9','Dorsalgia, unspecified','Musculoskeletal'),
('M62.6','Muscle strain','Musculoskeletal'),
('M65.9','Synovitis and tenosynovitis, unspecified','Musculoskeletal'),
('M67.4','Ganglion','Musculoskeletal'),
('M71.9','Bursopathy, unspecified','Musculoskeletal'),
('M75.0','Adhesive capsulitis of shoulder','Musculoskeletal'),
('M75.1','Rotator cuff syndrome','Musculoskeletal'),
('M76.6','Achilles tendinitis','Musculoskeletal'),
('M77.0','Medial epicondylitis','Musculoskeletal'),
('M77.1','Lateral epicondylitis','Musculoskeletal'),
('M79.1','Myalgia','Musculoskeletal'),
('M79.6','Pain in limb','Musculoskeletal'),
('M79.7','Fibromyalgia','Musculoskeletal'),
('M80.9','Osteoporosis with pathological fracture, unspecified','Musculoskeletal'),
('M81.9','Osteoporosis, unspecified','Musculoskeletal'),
('M94.9','Disorder of cartilage, unspecified','Musculoskeletal'),

-- Genitourinary
('N04.9','Nephrotic syndrome, unspecified','Genitourinary'),
('N10','Acute tubulo-interstitial nephritis','Genitourinary'),
('N18.3','Chronic kidney disease, stage 3','Genitourinary'),
('N18.5','Chronic kidney disease, stage 5','Genitourinary'),
('N18.9','Chronic kidney disease, unspecified','Genitourinary'),
('N19','Unspecified kidney failure','Genitourinary'),
('N20.0','Calculus of kidney','Genitourinary'),
('N20.1','Calculus of ureter','Genitourinary'),
('N23','Unspecified renal colic','Genitourinary'),
('N30.0','Acute cystitis','Genitourinary'),
('N30.9','Cystitis, unspecified','Genitourinary'),
('N39.0','Urinary tract infection, site not specified','Genitourinary'),
('N39.3','Stress incontinence','Genitourinary'),
('N40','Hyperplasia of prostate','Genitourinary'),
('N41.0','Acute prostatitis','Genitourinary'),
('N43.3','Hydrocele, unspecified','Genitourinary'),
('N45.9','Orchitis and epididymitis','Genitourinary'),
('N47','Redundant prepuce, phimosis and paraphimosis','Genitourinary'),
('N48.1','Balanoposthitis','Genitourinary'),
('N50.9','Disorder of male genital organs, unspecified','Genitourinary'),
('N60.1','Diffuse cystic mastopathy','Genitourinary'),
('N61','Inflammatory disorders of breast','Genitourinary'),
('N63','Unspecified lump in breast','Genitourinary'),
('N64.4','Mastodynia','Genitourinary'),
('N70.9','Salpingitis and oophoritis, unspecified','Genitourinary'),
('N72','Inflammatory disease of cervix uteri','Genitourinary'),
('N73.9','Female pelvic inflammatory disease, unspecified','Genitourinary'),
('N75.1','Abscess of Bartholin gland','Genitourinary'),
('N76.0','Acute vaginitis','Genitourinary'),
('N80.9','Endometriosis, unspecified','Genitourinary'),
('N83.2','Other and unspecified ovarian cysts','Genitourinary'),
('N84.0','Polyp of corpus uteri','Genitourinary'),
('N85.9','Noninflammatory disorder of uterus, unspecified','Genitourinary'),
('N87.9','Dysplasia of cervix uteri, unspecified','Genitourinary'),
('N91.2','Amenorrhoea, unspecified','Genitourinary'),
('N92.0','Excessive and frequent menstruation with regular cycle','Genitourinary'),
('N92.6','Irregular menstruation, unspecified','Genitourinary'),
('N93.9','Abnormal uterine and vaginal bleeding, unspecified','Genitourinary'),
('N94.6','Dysmenorrhoea, unspecified','Genitourinary'),
('N95.1','Menopausal and female climacteric states','Genitourinary'),
('N97.9','Female infertility, unspecified','Genitourinary'),

-- Pregnancy and perinatal
('O10.9','Pre-existing hypertension complicating pregnancy','Pregnancy'),
('O13','Gestational hypertension','Pregnancy'),
('O14.9','Pre-eclampsia, unspecified','Pregnancy'),
('O21.0','Mild hyperemesis gravidarum','Pregnancy'),
('O24.4','Diabetes mellitus arising in pregnancy','Pregnancy'),
('O80','Single spontaneous delivery','Pregnancy'),
('O99.0','Anaemia complicating pregnancy and the puerperium','Pregnancy'),
('P07.3','Other preterm infants','Perinatal'),
('P59.9','Neonatal jaundice, unspecified','Perinatal'),
('Q21.0','Ventricular septal defect','Congenital'),
('Q53.9','Undescended testicle, unspecified','Congenital'),
('Q54.9','Hypospadias, unspecified','Congenital'),

-- Symptoms and signs
('R00.0','Tachycardia, unspecified','Symptoms'),
('R03.0','Elevated blood-pressure reading without diagnosis of hypertension','Symptoms'),
('R04.0','Epistaxis','Symptoms'),
('R05','Cough','Symptoms'),
('R06.0','Dyspnoea','Symptoms'),
('R06.2','Wheezing','Symptoms'),
('R07.0','Pain in throat','Symptoms'),
('R07.4','Chest pain, unspecified','Symptoms'),
('R10.0','Acute abdomen','Symptoms'),
('R10.1','Pain localized to upper abdomen','Symptoms'),
('R10.4','Other and unspecified abdominal pain','Symptoms'),
('R11','Nausea and vomiting','Symptoms'),
('R12','Heartburn','Symptoms'),
('R13','Dysphagia','Symptoms'),
('R14','Flatulence and related conditions','Symptoms'),
('R17.9','Unspecified jaundice','Symptoms'),
('R18','Ascites','Symptoms'),
('R19.7','Diarrhoea, unspecified','Symptoms'),
('R20.2','Paraesthesia of skin','Symptoms'),
('R21','Rash and other nonspecific skin eruption','Symptoms'),
('R22.9','Localized swelling, mass and lump, unspecified','Symptoms'),
('R25.1','Tremor, unspecified','Symptoms'),
('R30.0','Dysuria','Symptoms'),
('R31','Unspecified haematuria','Symptoms'),
('R33','Retention of urine','Symptoms'),
('R35','Polyuria','Symptoms'),
('R42','Dizziness and giddiness','Symptoms'),
('R50.9','Fever, unspecified','Symptoms'),
('R51','Headache','Symptoms'),
('R52.9','Pain, unspecified','Symptoms'),
('R53','Malaise and fatigue','Symptoms'),
('R55','Syncope and collapse','Symptoms'),
('R56.8','Other and unspecified convulsions','Symptoms'),
('R59.9','Enlarged lymph nodes, unspecified','Symptoms'),
('R60.0','Localized oedema','Symptoms'),
('R60.1','Generalized oedema','Symptoms'),
('R63.0','Anorexia','Symptoms'),
('R63.4','Abnormal weight loss','Symptoms'),
('R63.5','Abnormal weight gain','Symptoms'),
('R73.9','Hyperglycaemia, unspecified','Symptoms'),
('R79.9','Abnormal finding of blood chemistry, unspecified','Symptoms'),

-- Injury and poisoning
('S00.9','Superficial injury of head, part unspecified','Injury'),
('S01.9','Open wound of head, part unspecified','Injury'),
('S06.0','Concussion','Injury'),
('S13.4','Sprain and strain of cervical spine','Injury'),
('S20.2','Contusion of thorax','Injury'),
('S33.5','Sprain and strain of lumbar spine','Injury'),
('S52.9','Fracture of forearm, part unspecified','Injury'),
('S61.9','Open wound of wrist and hand, part unspecified','Injury'),
('S62.9','Fracture of wrist and hand, part unspecified','Injury'),
('S72.9','Fracture of femur, part unspecified','Injury'),
('S82.9','Fracture of lower leg, part unspecified','Injury'),
('S83.6','Sprain and strain of other parts of knee','Injury'),
('S93.4','Sprain and strain of ankle','Injury'),
('T14.0','Superficial injury of unspecified body region','Injury'),
('T14.1','Open wound of unspecified body region','Injury'),
('T14.9','Injury, unspecified','Injury'),
('T30.0','Burn of unspecified body region, unspecified degree','Injury'),
('T63.4','Toxic effect of venom of other arthropods','Injury'),
('T78.2','Anaphylactic shock, unspecified','Injury'),
('T78.3','Angioneurotic oedema','Injury'),
('T78.4','Allergy, unspecified','Injury'),

-- Factors influencing health status
('Z00.0','General medical examination','Factors'),
('Z01.4','Gynaecological examination','Factors'),
('Z27.9','Need for immunization against unspecified infectious disease','Factors'),
('Z30.9','Contraceptive management, unspecified','Factors'),
('Z33','Pregnant state, incidental','Factors'),
('Z34.9','Supervision of normal pregnancy, unspecified','Factors'),
('Z35.9','Supervision of high-risk pregnancy, unspecified','Factors'),
('Z39.1','Care and examination of lactating mother','Factors'),
('Z71.3','Dietary counselling and surveillance','Factors'),
('Z76.0','Encounter for issue of repeat prescription','Factors')

on conflict (code) do nothing;
